### ISSUE TITLE
Error during install (QGIS 2)

### ISSUE THREAD

**Issue by jamaa** [lutraconsulting/qgis-crayfish-plugin#374]
I am getting the following error when trying to install the Crayfish plugin in QGIS 2.18. This is after the the necessary precompiled library has been downloaded and is located in the plugin directory.

I saw a number of older issues with the same error message (#104, #229) but did not see a solution to the problem other than using a newer version. 

I am using the latest version of QGIS 2.18 and the plugin offered in the official repository. I cannot migrate to QGIS 3 (yet) as there are still some deficiencies in QGIS 3 related to mesh layers.

```
Konnte Erweiterung crayfish nicht laden aufgrund eines Fehlers beim Aufruf der initGui() Methode 

WindowsError: [Error 126] Das angegebene Modul wurde nicht gefunden 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 342, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/[...]/.qgis2/python/plugins\crayfish\plugin.py", line 72, in initGui
    if not ensure_library_installed():
  File "C:/Users/[...]/.qgis2/python/plugins\crayfish\gui\install_helper.py", line 125, in ensure_library_installed
    load_library()
  File "C:/Users/[...]/.qgis2/python/plugins\crayfish\core.py", line 78, in load_library
    lib = ctypes.cdll.LoadLibrary(libpath)
  File "C:\OSGEO4~1\apps\Python27\lib\ctypes\__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "C:\OSGEO4~1\apps\Python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] Das angegebene Modul wurde nicht gefunden


Python-Version: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] 
QGIS-Version: 2.18.28 Las Palmas, aa30730ac6 

Python-Pfad:
C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing
C:/OSGEO4~1/apps/qgis-ltr/./python
C:/Users/[...]/.qgis2/python
C:/Users/[...]/.qgis2/python/plugins
C:/OSGEO4~1/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.4\apps\Python37
C:\OSGeo4W64\bin
C:\OSGEO4~1\bin\python27.zip
C:\OSGEO4~1\apps\Python27\DLLs
C:\OSGEO4~1\apps\Python27\lib
C:\OSGEO4~1\apps\Python27\lib\plat-win
C:\OSGEO4~1\apps\Python27\lib\lib-tk
C:\OSGEO4~1\bin
C:\OSGEO4~1\apps\Python27
C:\OSGEO4~1\apps\Python27\lib\site-packages
C:\OSGEO4~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\win32
C:\OSGEO4~1\apps\Python27\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python27\lib\site-packages\Pythonwin
C:\OSGEO4~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\OSGEO4~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/[...]/.qgis2//python
```
Fresh installs of QGIS and the plugin did not help, btw. 

Also, this is on operating system Windows 10.

**Comment by PeterPetrik** [comment]
Hi, @jamaa QGIS 2.18 is not longer supported, on Friday we released QGIS 3.4 as LTR. Crayfish for QGIS 2.x version is not supported either. If your project relies on QGIS 2.x and Crayfish, please contact our support for commercial support packages.

In QGIS 3.6, almost all functionality is ported to new "mesh layer", so I doubt it cannot be used for your project.

**Comment by jamaa** [comment]
Thanks for the reply. I was hoping you could point me to a quick fix to my installation issue. 

As you have said, "almost all" functionality has been ported to QGIS 3.6. In my view, it still cannot compete with Crayfish in QGIS2. See e.g. #354. Thus I will still be working with QGIS2.

**Comment by PeterPetrik** [comment]
unfortunately there is no quick fix how to solve this. We would need to install new VisualStudio ( few GBs) on Windows10 machine with recent QGIS 2.x, compile the binary and distribute it on our webpages. This must be done manually and could easily take up a day.
This was the main driver to abandon C++ library and implement MDAL/Mesh Layer natively in QGIS 3.x

**Comment by saberraz** [comment]
Please downgrade your QGIS to:
https://qgis.org/downloads/QGIS-OSGeo4W-2.18.16-1-Setup-x86_64.exe

It should work with Crayfish 2.7.2 release.

**Comment by jamaa** [comment]
Thanks a lot, it works with that version of QGIS!

**Comment by saberraz** [comment]
@jamaa Crayfish 2.x is obsolete. Everything is possible and we can make the new version better than the old (which already is).

If you need a specific feature missing. contact us for an estimate.
